// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5KwqykT9fuj0Q6NG07ezoConlpY9oJLo',
    appId: '1:42242203473:web:54151fb7b5a76ebc60bd70',
    messagingSenderId: '42242203473',
    projectId: 'vantage-3c746',
    authDomain: 'vantage-3c746.firebaseapp.com',
    storageBucket: 'vantage-3c746.firebasestorage.app',
    measurementId: 'G-VFRQJVZB60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKd3ASDESNGyY6qrzoDakEv4Iex-8vaRU',
    appId: '1:42242203473:android:bf39d53c299e6aed60bd70',
    messagingSenderId: '42242203473',
    projectId: 'vantage-3c746',
    storageBucket: 'vantage-3c746.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRELbjaGJdC8eqtYtpO3CaE6oLwsSGjsc',
    appId: '1:42242203473:ios:c0d8462b68fd380760bd70',
    messagingSenderId: '42242203473',
    projectId: 'vantage-3c746',
    storageBucket: 'vantage-3c746.firebasestorage.app',
    iosClientId: '42242203473-makoe9i1u4ujd0f8qpvq95pbc7fslr7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.vantage',
  );
}
